name: 02- Push Main Workflow

on:
 push:
  branches:
   - main

jobs:
  push-test:
   name: Test push trigger 
   runs-on: ubuntu-latest

   steps:
   - name: show event name
     run: echo  "Event name  is ${{github.event.name}}"
   
   - name: Show git ref 
     run: echo "Git ref is ${{github.ref}}"
   - name: Show actor
     run: echo  "Triggered by ${{github.actor}}"

    
    
