name: 06 - Workflow Configuration Practice

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

      runTests:
        description: 'Run test step?'
        required: true
        default: true
        type: boolean

  schedule:
    - cron: '25 16 26 5 *'

jobs:
  test-config:
    name: Test workflow config
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger info
        run: |
          echo "Workflow triggered!"
          echo "Event name: ${{ github.event_name }}"
          echo "Selected environment: ${{ inputs.environment }}"
          echo "Run tests: ${{ inputs.runTests }}"